// docs/*.md → src/docs.ts (one static module: every page is in the entry chunk, so a prerendered page never flashes
// while a view chunk loads), public/docs/<slug>.md (the sources, for agents) and public/llms.txt.
// The browser gets nodes, not HTML: the production CSP blocks innerHTML, so markdown is parsed here, once.
import { marked } from 'marked';
import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

const ORIGIN = 'https://jasno.dev';
const TAGLINE = 'A TypeScript-first framework for single-page apps. Plain TypeScript: no JSX, no template language, no build configuration.';

const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', '#39': "'" };
const decode = (s) => s.replace(/&(amp|lt|gt|quot|#39);/g, (_, e) => ENTITIES[e]);
const plain = (tokens) => tokens.map((t) => (t.tokens ? plain(t.tokens) : t.text ?? '')).join('');
const anchor = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/** marked tokens → nodes: a string, or [tag, props, children]. */
const conv = (tokens) => tokens.flatMap(node);
function node(t) {
  switch (t.type) {
    case 'space': case 'html': case 'def': return [];
    case 'text': return t.tokens ? conv(t.tokens) : [decode(t.text)];
    case 'escape': return [t.text];
    case 'heading': return [[`h${t.depth}`, { id: anchor(plain(t.tokens)) }, conv(t.tokens)]];
    case 'paragraph': return [['p', null, conv(t.tokens)]];
    case 'code': return [['pre', null, [['code', t.lang ? { class: `language-${t.lang}` } : null, [t.text]]]]];
    case 'codespan': return [['code', null, [t.text]]];
    case 'blockquote': return [['blockquote', null, conv(t.tokens)]];
    case 'list': return [[t.ordered ? 'ol' : 'ul', t.ordered && t.start !== 1 ? { start: t.start } : null,
      t.items.map((i) => ['li', null, conv(i.tokens)])]];
    case 'hr': case 'br': return [[t.type, null, []]];
    case 'strong': case 'em': case 'del': return [[t.type, null, conv(t.tokens)]];
    case 'link': return [['a', { href: t.href }, conv(t.tokens)]];
    case 'image': return [['img', { src: t.href, alt: t.text }, []]];
    case 'table': return [['table', null, [
      ['thead', null, [['tr', null, t.header.map((c) => ['th', null, conv(c.tokens)])]]],
      ['tbody', null, t.rows.map((r) => ['tr', null, r.map((c) => ['td', null, conv(c.tokens)])])],
    ]]];
    default: throw new Error(`build-docs: unhandled markdown token "${t.type}"`);
  }
}

const docs = {};
rmSync('public/docs', { recursive: true, force: true }); // a deleted page leaves no stale copy behind
mkdirSync('public/docs', { recursive: true });
for (const f of readdirSync('docs').filter((f) => f.endsWith('.md')).sort()) {
  const slug = f.slice(0, -3);
  const tokens = marked.lexer(readFileSync(`docs/${f}`, 'utf8'));
  const h1 = tokens.find((t) => t.type === 'heading' && t.depth === 1);
  if (!h1) throw new Error(`build-docs: docs/${f} has no "# Title"`);
  docs[slug] = { title: plain(h1.tokens), nodes: conv(tokens) };
  copyFileSync(`docs/${f}`, `public/docs/${f}`);
}

writeFileSync('src/docs.ts', `// Generated by scripts/build-docs.mjs from docs/*.md; do not edit.
import type { Doc } from './md.ts';

export const docs: Readonly<Record<string, Doc>> = ${JSON.stringify(docs)};
`);
writeFileSync('public/llms.txt', `# jasno

> ${TAGLINE}

## Docs

${Object.entries(docs).map(([slug, d]) => `- [${d.title}](${ORIGIN}/docs/${slug}.md)`).join('\n')}

## API

- [AGENTS.md](https://raw.githubusercontent.com/cesbo/jasno/HEAD/design/AGENTS.md): the guide for coding agents, copied into every new project
- [jasno.d.ts](https://raw.githubusercontent.com/cesbo/jasno/HEAD/design/jasno.d.ts): the whole API with a RECIPES block of common patterns
`);
console.log(`build-docs: ${Object.keys(docs).length} pages → src/docs.ts, public/docs/, public/llms.txt`);
